# Create data to pull up the database.
CALL create_account('Nyckolaxx');
CALL create_account('Mega');
CALL create_account('Mithivi');
CALL create_account('Nakia');
CALL create_account('Nokia');
CALL create_account('Vingt');
CALL create_account('Renaud');

CALL create_tamagotchi(1, 'Crane');
CALL create_tamagotchi(1, 'Liesl');
CALL create_tamagotchi(2, 'Merrill');
CALL create_tamagotchi(3, 'Moreno');
CALL create_tamagotchi(4, 'Baxter');
CALL create_tamagotchi(5, 'Ida');
CALL create_tamagotchi(6, 'Mendoza');
CALL create_tamagotchi(7, 'Cannon');
CALL create_tamagotchi(7, 'Lindsay');
CALL create_tamagotchi(1, 'Kari');
CALL create_tamagotchi(5, 'Blankenship');
CALL create_tamagotchi(6, 'Ayers');

DO SLEEP(5);

CALL bedtime(1);
CALL eat(1);
CALL enjoy(1);
CALL drink(1);
CALL eat(1);
CALL enjoy(1);
CALL drink(1);
CALL enjoy(1);
CALL bedtime(1);
CALL drink(1);
CALL eat(1);
CALL enjoy(1);
CALL enjoy(1);
CALL enjoy(1);
CALL enjoy(1);
CALL bedtime(1);
CALL drink(1);
CALL eat(1);
CALL enjoy(1);
CALL enjoy(1);
CALL drink(1);
CALL eat(1);
CALL bedtime(1);
CALL drink(1);
CALL enjoy(1);
CALL enjoy(1);
CALL eat(1);
CALL drink(1);
CALL bedtime(1);
CALL eat(1);
CALL enjoy(1);
CALL enjoy(1);
CALL drink(1);
CALL bedtime(1);
CALL eat(1);
CALL enjoy(1);
CALL drink(1);
CALL drink(1);
CALL eat(1);
CALL bedtime(1);
CALL enjoy(1);
CALL enjoy(1);
CALL eat(1);
CALL drink(1);
CALL bedtime(1);
CALL enjoy(1);
CALL enjoy(1);
CALL eat(1);
CALL drink(1);
CALL enjoy(1);
CALL bedtime(1);
CALL eat(1);
CALL drink(1);
CALL drink(1);
CALL eat(1);
CALL bedtime(1);

CALL bedtime(2);
CALL eat(2);
CALL enjoy(2);
CALL drink(2);
CALL eat(2);
CALL enjoy(2);
CALL drink(2);
CALL enjoy(2);
CALL bedtime(2);

CALL bedtime(4);
CALL eat(4);
CALL enjoy(4);
CALL drink(4);
CALL eat(4);
CALL enjoy(4);
CALL drink(4);
CALL enjoy(4);
CALL bedtime(4);
CALL drink(4);
CALL eat(4);
CALL enjoy(4);
CALL enjoy(4);
CALL enjoy(4);
CALL enjoy(4);
CALL bedtime(4);
CALL drink(4);
CALL eat(4);
CALL enjoy(4);
CALL enjoy(4);

CALL bedtime(10);
CALL eat(10);
CALL enjoy(10);
CALL drink(10);
CALL eat(10);
CALL enjoy(10);
CALL drink(10);
CALL enjoy(10);
CALL bedtime(10);
CALL drink(10);
CALL eat(10);
CALL enjoy(10);
CALL enjoy(10);
CALL enjoy(10);
CALL enjoy(10);
CALL bedtime(10);
CALL drink(10);
CALL eat(10);
CALL enjoy(10);
CALL enjoy(10);

CALL bedtime(7);
CALL eat(7);
CALL enjoy(7);
CALL drink(7);

CALL bedtime(5);
CALL eat(5);
CALL enjoy(5);
CALL drink(5);
CALL eat(5);
CALL enjoy(5);
CALL drink(5);
CALL enjoy(5);
CALL bedtime(5);
CALL drink(5);